// Code generated by command: go run generate.go -out add.s -stubs stub.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func FindHashes(tophashes *[16]uint8, triehashes *[16]uint8, tophash8 uint8, triehash8 uint8) uint16
// Requires: SSE2, SSSE3
TEXT ·FindHashes(SB), NOSPLIT, $0-26
	MOVQ     tophashes+0(FP), AX
	MOVQ     triehashes+8(FP), CX
	MOVBLZX  tophash8+16(FP), DX
	MOVBLZX  triehash8+17(FP), BX
	MOVD     DX, X0
	MOVD     BX, X2
	PXOR     X1, X1
	PSHUFB   X1, X0
	PSHUFB   X1, X2
	MOVOU    (AX), X1
	MOVOU    (CX), X3
	PCMPEQB  X1, X0
	PCMPEQB  X3, X2
	PAND     X2, X0
	PMOVMSKB X0, AX
	MOVW     AX, ret+24(FP)
	RET

// func FindEmpty(tophashes *[16]uint8) uint16
// Requires: SSE2
TEXT ·FindEmpty(SB), NOSPLIT, $0-10
	MOVQ     tophashes+0(FP), AX
	MOVOU    (AX), X1
	PXOR     X0, X0
	PCMPEQB  X1, X0
	PMOVMSKB X0, AX
	MOVW     AX, ret+8(FP)
	RET

// func FindPresent(tophashes *[16]uint8) uint16
// Requires: SSE2, SSSE3
TEXT ·FindPresent(SB), NOSPLIT, $0-10
	MOVQ     tophashes+0(FP), AX
	MOVQ     $0x000000000000007f, CX
	MOVQ     CX, X0
	PXOR     X1, X1
	PSHUFB   X1, X0
	MOVOU    (AX), X1
	PAND     X1, X0
	PXOR     X1, X1
	PCMPGTB  X1, X0
	PMOVMSKB X0, AX
	MOVW     AX, ret+8(FP)
	RET
