// Code generated by command: go run generate.go -out add.s -stubs stub.go. DO NOT EDIT.

//go:build amd64

package asm

//go:noescape
func FindHashesAndEmpties(tophashes *[16]uint8, triehashes *[16]uint8, tophash8 uint8, triehash8 uint8) (hashes uint16, empties uint16)

//go:noescape
func FindEmpty(tophashes *[16]uint8) uint16

//go:noescape
func FindBytesWhereBitsRemainSetAfterApplyingThisMask(hashes *[16]uint8, mask uint8) uint16
